spring:
  main:
    web-application-type: NONE

  output:
    ansi:
      enabled: ALWAYS

service:
  spark:
    mode: yarn

storage:
  read: /datasets
  write: /datasets/write

reader:
  spark-mode: PERMISSIVE
  corrupt-records:
    enabled: true

  schema:
    enabled: true
    name: flight
    print-enabled: true
  header-enabled: true

writer:
  corrupt-records:
    write: true
    header-enabled: true
  header-enabled: true
  postfix-date:
    enabled: true